### ISSUE TITLE
Vulnerability in ocall_read_db

### ISSUE THREAD

**Issue by reuvenpo** [enigmampc/SecretNetwork#133]
While reviewing some things around the enclave boundary i realized there is a data-leakage vulnerability in `ocall_read_db`.
Since the enclave is run by untrusted hosts, it can not trust values returned from that host. This means inputs to ecalls, can return values of ocalls.
The `ocall_read_db` method is part of the following sequence of operations:
* The host calls the `ecall_init`/`ecall_handle`/`ecall_query` function
* A WASM runtime is started with a module and the appropriate function in it is called
* The WASM module requests to read a from the KV storage (DB)
* The `ocall_read_db` function is called
* The KV storage fetches the value of the key and returns it
* The host calls `ecall_allocate` to copy the value into the enclave memory
* `ecall_allocate` allocates a `Box<Vec<u8>>` and returns it as `EnclavePointer`
* This pointer is then returned as is from `ocall_read_db` and the enclave retrieves the vector.
* The buffer is copied into the WASM memory space where the secret contract can read form it.

Now, if a malicious host instead returns a pointer to something that _looks_ like a vector to an area of memory inside the enclave that should be kept secret, the contract will read it instead, treat it as the return value of the `read_db` operation, and might include it in the JSON it returns out of the enclave when it finishes running (and `ecall_init`/`ecall_handle`/`ecall_query` return from the enclave).
If done accurately, this may leak either sensitive user data, secret keys, or anything else that can gradually break the whole security network.

There are two solutions to this:
1. We encrypt the pointer that returns from `ecall_allocate` - but then which keys should we use for that?
2. Add a `hash` field to `EnclaveBuffer` that shows the hash of the data inside the buffer. That way, an attacker will have to know ahead of time what information he expects to find behind the pointer (which isn't great) and can still cause Use-After-Free or other allocator errors errors if he gives us dubious addresses.

Ideally, we would employ both techniques in tandem.

**Comment by reuvenpo** [comment]
Another option is to have a static global variable with a `HashSet<*mut c_void>` (a set of pointers) which would keep track of which addresses represent memory that was allocated but not yet freed. This way if `ocall_read_db` returns an address that is not recognized, we try to call it again. This way the worst case scenario is that the host forces us into an infinite loop that allocates more and more memory, until the enclave crashes from an allocator fault.

**Comment by reuvenpo** [comment]
After some discussion in the team, we realized that if the keys are encrypted with something like aes256gcm we can validate that the content in the vector is valid. If we fail to decrypt it, that means that we have been given a pointer to an invalid memory location, and all we have to do is [mem::forget](https://doc.rust-lang.org/std/mem/fn.forget.html) the `Box<Vec<u8>>` that we interpreted the pointer as.

**Comment by guyz** [comment]
Just to clarify, the idea is as follows:
**Write**: when writing to the KV store (initiated inside of the enclave), encrypt the value with the _state key_ only known to the enclave itself. Also, add the hash of the key (as in the key in the key-value pair, not an encryption key) as extended data to the encryption.

The (key, ciphertext) pair is passed outside of the enclave and stored by CosmWasm in the node's filesystem. 

**Read**: when reading from the KV store a request is sent outside of the enclave to fetch the value pertaining to a specific key. This means leaving the enclave, and that's where the risk is - a malicious host can either:
1. change the data being read
2. change the pointer addressing the data being read

That's why the solution seems to be to encrypt the data with a key only known inside of the enclave should resolve the problem of a malicious host trying to encrypt their own data. Hashing the key (again, NOT encryption key) and adding it as extended data to their encryption will ensure that it is authenticated as well. As such, a malicious host can't replace the data with a different data that was previously encrypted by the enclave (this could be used, for example, to make the enclave a 'decryption oracle').

**Comment by assafmo** [comment]
Is this still relevant?

**Comment by reuvenpo** [comment]
Yes, very. This is also related to other memory bugs we described when trusting pointers passed in from the host. The code calling `ocall_read_db` needs to be implemented extremely carefully, or else the host can hijack the execution inside the enclave.
